# Generated by Django 4.2.1 on 2023-06-02 11:44

import clickhouse_backend.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_id', clickhouse_backend.models.StringField()),
                ('link', clickhouse_backend.models.StringField()),
                ('label', clickhouse_backend.models.StringField()),
                ('company_name', clickhouse_backend.models.StringField()),
                ('company_cover', clickhouse_backend.models.StringField()),
                ('company_website', clickhouse_backend.models.StringField()),
                ('company_category', clickhouse_backend.models.StringField()),
                ('title', clickhouse_backend.models.StringField()),
                ('category', clickhouse_backend.models.StringField()),
                ('location', clickhouse_backend.models.StringField()),
                ('type_cooperation', clickhouse_backend.models.StringField()),
                ('work_experience', clickhouse_backend.models.StringField()),
                ('salary', clickhouse_backend.models.StringField()),
                ('description', clickhouse_backend.models.StringField()),
                ('company_about', clickhouse_backend.models.StringField()),
                ('gender', clickhouse_backend.models.StringField()),
                ('education', clickhouse_backend.models.StringField()),
                ('military_service', clickhouse_backend.models.StringField()),
                ('skills', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.StringField())),
                ('date_last_crawl', clickhouse_backend.models.StringField()),
                ('publication_date', clickhouse_backend.models.Int8Field()),
            ],
            options={
                'verbose_name': 'Jobs',
                'db_table': 'jobdarjob_single',
                'ordering': ['-publication_date'],
                'engine': clickhouse_backend.models.ReplacingMergeTree(order_by=['publication_date']),
            },
        ),
    ]
