# Generated by Django 4.2.1 on 2023-06-02 13:33

import clickhouse_backend.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=clickhouse_backend.models.UUIDField(default=uuid.UUID('c84d6c00-d3f6-427a-9fdd-951002daaf30'), primary_key=True, serialize=False),
        ),
    ]
